### ISSUE TITLE
更新红白玫瑰program、宣传片YouTube链接(B站链接无需更新)

### ISSUE THREAD

**Issue by Meng-V** [SayingTheatreClub/SayingWebFrontend#19]
更新红白玫瑰program https://drive.google.com/file/d/1TQfkldbuwy02rqvDob7TgDF6WhyY2pgF/view?usp=sharing 、宣传片YouTube链接 https://youtu.be/hhGodhDvVCk (B站链接无需更新)

- [x] 首页 (宣传片)

- [x] 红白玫瑰页面 (宣传片)

- [x] 红白玫瑰页面 (program)

**Comment by SayingTheatre** [comment]
Done
